# Microservice level resources (if defined will override default resources)
# *******************************************************
# microservice:
#   wfb-service:
#     minReplicas: 1
#     maxReplicas: 3
#     resources:
#       requests:
#         cpu: 50m
#         memory: 250Mi
#       limits:
#         cpu: 100m
#         memory: 500Mi
# *******************************************************

microservicesName:
  wfb-api-service:
    autoscalingMinReplicas: 1
    autoscalingMaxReplicas: 5

configMap:
  data:
    NODE_ENV: dev
    LOG_LEVEL: info
    PORT: "5000"
    ENV: dev

    KAFKA_HOST: "b-3.zeusbasesharedpreprod.68d6s9.c14.kafka.us-west-2.amazonaws.com:9094,b-1.zeusbasesharedpreprod.68d6s9.c14.kafka.us-west-2.amazonaws.com:9094,b-2.zeusbasesharedpreprod.68d6s9.c14.kafka.us-west-2.amazonaws.com:9094"

    AWS_SM_REGION: us-west-2
    AWS_SM_API_VERSION:  "2017-10-17"
    AWS_SM_KMS_KEY_ID: "4e4743d9-3b5c-45dc-b795-64a5dc995e86"
    AWS_SM_HARNESS_CREDS_KEY_NAME: "dev/harness"

    USER_EVENTS_KAFKA_TOPIC: 'Zeus_Identity_User_Dev'
    MANAGE_ACCOUNTS_KAFKA_TOPIC: 'Zeus_Account_App_Manage_Account_Dev'

    SIMPPLR_IDENTITY_MGMT_MS_BASE_URL: http://identity-mgmt-service
    SIMPPLR_AQUA_SERVICE_MS_BASE_URL: http://wfb-api-service

    VAULT_HARNESS_CREDS_KEY_NAME: "infra/dev/static/harness"
    VAULT_SECRET_NAME: 'vault/dev/beta'
    MONGODB_SECRET_NAME: "infra/dev/static/db"

    OBSERVABILITY_ENABLED: 'Y'


